services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - app-network
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
